f = open("p.txt", "r")
print("Before changing:")
print(f.read())
f = open("p.txt", "a")
statement1 = input("Enter first statement: ")
f.write("\n" + statement1)
statement2 = input("Enter second statement: ")
f.write("\n" + statement2)
f.close()
f = open("p.txt", "r")
print("After changing:")
print(f.read())
